# Generated by Django 5.0.6 on 2024-05-10 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiset', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('description', models.TextField()),
            ],
        ),
    ]
